//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebStoreMVC.Application.Resources {
    using System;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ErrorMessage {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ErrorMessage() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("WebStoreMVC.Application.Resources.ErrorMessage", typeof(ErrorMessage).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static string RolesAlreadyExists {
            get {
                return ResourceManager.GetString("RolesAlreadyExists", resourceCulture);
            }
        }
        
        internal static string UserAlreadyExists {
            get {
                return ResourceManager.GetString("UserAlreadyExists", resourceCulture);
            }
        }
        
        internal static string ModelCreatingIsFalied {
            get {
                return ResourceManager.GetString("ModelCreatingIsFalied", resourceCulture);
            }
        }
        
        internal static string IncorrectCredentials {
            get {
                return ResourceManager.GetString("IncorrectCredentials", resourceCulture);
            }
        }
        
        internal static string IncorrectToken {
            get {
                return ResourceManager.GetString("IncorrectToken", resourceCulture);
            }
        }
        
        internal static string UserDoesNotExist {
            get {
                return ResourceManager.GetString("UserDoesNotExist", resourceCulture);
            }
        }
        
        internal static string UserAlreadyIsAdmin {
            get {
                return ResourceManager.GetString("UserAlreadyIsAdmin", resourceCulture);
            }
        }
        
        internal static string AccessError {
            get {
                return ResourceManager.GetString("AccessError", resourceCulture);
            }
        }
        
        internal static string ProductsAreNotFound {
            get {
                return ResourceManager.GetString("ProductsAreNotFound", resourceCulture);
            }
        }
        
        internal static string ProductAlreadyExists {
            get {
                return ResourceManager.GetString("ProductAlreadyExists", resourceCulture);
            }
        }
        
        internal static string InternalServerError {
            get {
                return ResourceManager.GetString("InternalServerError", resourceCulture);
            }
        }
        
        internal static string TokenIsNullOrNotFound {
            get {
                return ResourceManager.GetString("TokenIsNullOrNotFound", resourceCulture);
            }
        }
        
        internal static string CartIsEmpty {
            get {
                return ResourceManager.GetString("CartIsEmpty", resourceCulture);
            }
        }
        
        internal static string GettingOrderDataIsFailed {
            get {
                return ResourceManager.GetString("GettingOrderDataIsFailed", resourceCulture);
            }
        }
        
        internal static string OrderDeletingIsFailed {
            get {
                return ResourceManager.GetString("OrderDeletingIsFailed", resourceCulture);
            }
        }
        
        internal static string FailureToShowOrderInfo {
            get {
                return ResourceManager.GetString("FailureToShowOrderInfo", resourceCulture);
            }
        }
        
        internal static string FailureToGetUserDeliveryInfo {
            get {
                return ResourceManager.GetString("FailureToGetUserDeliveryInfo", resourceCulture);
            }
        }
    }
}
