//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebStoreMVC.Application.Resources {
    using System;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class SuccessMessage {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SuccessMessage() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("WebStoreMVC.Application.Resources.SuccessMessage", typeof(SuccessMessage).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static string CreatingRolesIsDone {
            get {
                return ResourceManager.GetString("CreatingRolesIsDone", resourceCulture);
            }
        }
        
        internal static string CreatingUserIsDone {
            get {
                return ResourceManager.GetString("CreatingUserIsDone", resourceCulture);
            }
        }
        
        internal static string UpgradeUserToAdmin {
            get {
                return ResourceManager.GetString("UpgradeUserToAdmin", resourceCulture);
            }
        }
        
        internal static string DowngradeAdminToUser {
            get {
                return ResourceManager.GetString("DowngradeAdminToUser", resourceCulture);
            }
        }
        
        internal static string LogoutIsDone {
            get {
                return ResourceManager.GetString("LogoutIsDone", resourceCulture);
            }
        }
        
        internal static string ProductsAreReceived {
            get {
                return ResourceManager.GetString("ProductsAreReceived", resourceCulture);
            }
        }
        
        internal static string CreatingCartVM {
            get {
                return ResourceManager.GetString("CreatingCartVM", resourceCulture);
            }
        }
        
        internal static string OperationForCart {
            get {
                return ResourceManager.GetString("OperationForCart", resourceCulture);
            }
        }
    }
}
