version: "3.6"
services:
  webstoremvc:
    build:
      context: .
      dockerfile: WebStoreMVC.Api/Dockerfile
    ports:
      - "8080:80"
    networks:
      - networknet
    volumes:
      - /c/temp-keys:/root/.aspnet/DataProtection-Keys
    depends_on:
      - postgres_db
  
  postgres_db:
    image: postgres:latest
    container_name: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: kt91ni79ol11
      POSTGRES_DB: WebStore
    ports:
      - "5438:5432"
    restart: always
    networks:
      - networknet
    volumes:
      - postgres-data:/var/lib/postgresql/data
        
volumes: 
  postgres-data:
      
networks:
  networknet:
    driver: bridge
