services:
  webstoremvc:
    build:
      context: ..
      dockerfile: WebStoreMVC.Api/Dockerfile
    ports:
      - "8080:8080"
    container_name: webstore_api
    depends_on:
      - postgres_db
    networks:
      - webstore-network

  postgres_db:
    image: postgres:latest
    container_name: postgres_container
    secrets:
      - pass
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: WebStore
    ports:
      - "5555:5555"
    restart: always
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - webstore-network

secrets:
  pass:
    file: ./secret

networks:
  webstore-network:
volumes:
  db_data: