# This is a generated file. Not intended for manual editing.
services:
  webstoremvc:
    build:
      context: "/home/alexander/RiderProjects/WebStoreMVC"
      dockerfile: "WebStoreMVC.Api/Dockerfile"
      target: "base"
    command: []
    entrypoint:
    - "dotnet"
    - "/app/bin/Debug/net8.0/WebStoreMVC.Api.dll"
    environment:
      ASPNETCORE_ENVIRONMENT: "Development"
      ASPNETCORE_STATICWEBASSETS: "/app/bin/Debug/net8.0/WebStoreMVC.Api.staticwebassets.runtime.CT.json"
      DOTNET_USE_POLLING_FILE_WATCHER: "true"
    image: "webstoremvc.api:dev"
    ports: []
    volumes:
    - "/home/alexander/.microsoft/usersecrets:/home/app/.microsoft/usersecrets"
    - "/home/alexander/.nuget/packages:/home/app/.nuget/packages"
    - "/home/alexander/RiderProjects/WebStoreMVC/WebStoreMVC.Api:/app:rw"
    - "/home/alexander/RiderProjects/WebStoreMVC:/src:rw"
    working_dir: "/app"
